export { default as Home} from './Home'
export { default as Login} from './Login'
export { default as Signup} from './Signup'
export { default as Settings} from './CreateProject'
export { default as Users} from './Users'
export { default as ProjectManagement} from './ProjectManagement'
export { default as ProjectDetail} from './ProjectDetail'