export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const LOGIN_INFO = 'LOGIN_INFO'
export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'
export const PROJECT_CATEGORY = 'PROJECT_CATEGORY'
export const ALL_PROJECT = 'ALL_PROJECT'
export const ALL_PROJECT_KEYWORD = 'ALL_PROJECT_KEYWORD'
export const USER_TOKEN = 'USER_TOKEN'
export const USER_INFO = 'USER_INFO'
export const OPEN_MODAL_EDIT = 'OPEN_MODAL_EDIT'
export const OPEN_MODAL_TASK = 'OPEN_MODAL_TASK'
export const CLOSE_MODAL_EDIT = 'CLOSE_MODAL_EDIT'
export const CLOSE_MODAL_TASK = 'CLOSE_MODAL_TASK'
export const PROJECT_DETAIL_INFO = 'PROJECT_DETAIL_INFO'
export const USER_LIST_INFO = 'USER_LIST_INFO'
export const MODAL_USER_EDIT_OPEN = 'MODAL_USER_EDIT_OPEN'
export const MODAL_USER_EDIT_CLOSE = 'MODAL_USER_EDIT_CLOSE'
export const EDIT_INFO_USER='EDIT_INFO_USER'
export const OPEN_ALERT_EDIT_USER ='OPEN_ALERT_EDIT_USER'
export const CLOSE_ALERT_EDIT_USER ='CLOSE_ALERT_EDIT_USER'
export const SAVE_INFO_USER='SAVE_INFO_USER'
export const CLOSE_MODAL_CREATE_USER='CLOSE_MODAL_CREATE_USER'
export const OPEN_MODAL_CREATE_USER=' OPEN_MODAL_CREATE_USER'
export const USER_PROJECT = 'USER_PROJECT'
export const ALL_TASK_TYPE = 'ALL_TASK_TYPE'
export const ALL_PRIORITY = 'ALL_PRIORITY'
export const ALL_USERS = 'ALL_USERS';
export const ALL_STATUS = 'ALL_STATUS';
export const USERS_BY_ID_PROJ = 'USERS_BY_ID_PROJ';
export const OPEN_MODAL_EDIT_TASK = 'OPEN_MODAL_EDIT_TASK';
export const CLOSE_MODAL_EDIT_TASK = 'CLOSE_MODAL_EDIT_TASK';
export const TASK_DETAIL = 'TASK_DETAIL';
export const EDIT_INFO_TASK_DETAIL = 'EDIT_INFO_TASK_DETAIL';
export const TASK_DETAIL_ASSIGN = 'TASK_DETAIL_ASSIGN';
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN';
export const TASK_DETAIL_ASSIGN_API = 'TASK_DETAIL_ASSIGN_API';
export const HANDLE_CHANGE_TASK_DETAIL = 'HANDLE_CHANGE_TASK_DETAIL';
export const TEST_TOKEN = 'TEST_TOKEN';
export const ALL_CMT = 'ALL_CMT';


 

// ----------------API------------------ //
export const OPEN_EDIT_USER = 'OPEN_EDIT_USER'
export const CLOSE_EDIT_USER = 'CLOSE_EDIT_USER'
 
export const LOGIN_API = 'LOGIN_API';
export const SIGN_UP_API = 'SIGN_UP_API'
export const TEST_TOKEN_API = 'TEST_TOKEN_API';
export const UPDATE_STATUS_DRAG = 'UPDATE_STATUS_DRAG';

export const PROJECT_CATEGORY_API = 'PROJECT_CATEGORY_API'
export const CREATE_PROJECT_API = 'CREATE_PROJECT_API'
export const GET_ALL_PROJECT_API = 'GET_ALL_PROJECT_API'
export const GET_PROJECT_DETAIL_API = 'GET_PROJECT_DETAIL_API'
export const UPDATE_PROJECT_API = 'UPDATE_PROJECT_API'
export const GET_LIST_USER_API = 'GET_LIST_USER_API'
export const GET_INFO_USER = 'GET_INFO_USER'
export const PUT_SAVE_INFO_USER='PUT_SAVE_INFO_USER'
export const DELETE_USER='DELETE_USER'
export const POST_CREATE_USER='POST_CREATE_USER'
export const SEARCH_USER_LIST = 'SEARCH_USER_LIST'
export const DELETE_PROJECT_API = 'DELETE_PROJECT_API'
export const GET_USER_PROJECT_API = 'GET_USER_PROJECT_API'
export const ASSIGN_USER_PROJECT_API = 'ASSIGN_USER_PROJECT_API'
export const REMOVE_USER_FROM_PROJ = 'REMOVE_USER_FROM_PROJ'
export const GET_ALL_PROJ_KEYWORD = 'GET_ALL_PROJ_KEYWORD'
export const CREATE_TASK_API = 'CREATE_TASK_API'
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE'
export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY'

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USERS_BY_ID_PROJECT = 'GET_USERS_BY_ID_PROJECT';

export const GET_ALL_STATUS = 'GET_ALL_STATUS';
export const GET_TASK_DETAIL_API = 'GET_TASK_DETAIL_API';
export const GET_ALL_CMT_API = 'GET_ALL_CMT_API';
 

